name: todo_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.9+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  drift: 2.35.0
  intl: 0.20.3
  flutter_bloc: 9.1.1
  path_provider: 2.1.6
  firebase_core: 4.15.0
  firebase_crashlytics: 5.4.0
  firebase_analytics: 12.6.0
  get_it: 9.3.0
  path: 1.9.1
  equatable: 3.0.0
  firebase_ai: 4.0.0
  uuid: 4.6.0
  speech_to_text: 7.5.0
  permission_handler: 13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: 6.0.0
  build_runner: ^2.16.1
  drift_dev: 2.35.0
  flutter_launcher_icons: 0.14.4
  bloc_test: 10.0.0
  mocktail: 1.0.4


# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app_icon.png"
  image_path_android: "assets/app_icon.png"
  adaptive_icon_background: "assets/app_icon_background.png"
  adaptive_icon_foreground: "assets/app_icon_foreground.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/
    - shorebird.yaml
